# keep scripts enabled by default
enableScripts: true

# disable scripts for @pendle/v2-sy
dependenciesMeta:
  "@pendle/v2-sy@*":
    # disable every lifecycle script this package defines
    scripts: false
