[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
"utils=lib/utils/",
"forge-std=lib/forge-std/src/",
"addressBook=lib/AddressBook/src/",
"@openzeppelin=lib/openzeppelin-contracts/",
"openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
"openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

ffi = true
optimizers_runs = 200

[rpc_endpoints]
ethereum = "https://eth.llamarpc.com"