[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 4
auto_detect_remappings = false
evm_version = "cancun"

remappings = [
"utils=lib/utils/",
"solady=lib/solady/",
"herdaddy=lib/herdaddy/src/",
"forge-std=lib/forge-std/src/",
"address-book=lib/address-book/src/",
"@openzeppelin=lib/openzeppelin-contracts/",
"openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
"solidity-examples/=lib/solidity-examples/contracts/",
"murky/=lib/murky/src/",
"LayerZero-v2/=lib/LayerZero-v2/",
"ds-test/=lib/forge-std/lib/ds-test/src/",
"solmate/=lib/solmate/src/"
]

ffi = true
optimizers_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config


[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
tdly = "https://rpc.tenderly.co/fork/07ccd43f-994b-4551-96b2-dc4c73778a60"
base = "https://mainnet.base.org"
bnb = "https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3	"
bnb_testnet = "https://bsc-testnet.publicnode.com"
fraxtal = "https://rpc.frax.com"