[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3

evm_version = "shanghai"

ffi = true

optimizers_runs = 200

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
bnb = "https://bsc-mainnet.nodereal.io/v1/8ba50235e5794af7ba04e88181bb359f"