[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3

remappings = [
"utils=lib/utils/",
"solady=lib/solady/",
"forge-std=lib/forge-std/src/",
"address-book=lib/address-book/src/",
"@openzeppelin=lib/openzeppelin-contracts/",
"openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
"solidity-examples/=lib/solidity-examples/contracts/",
"LayerZero-v2/=lib/LayerZero-v2/oapp/contracts",
"@layerzerolabs=node_modules/@layerzerolabs"
]

ffi = true
optimizers_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config


[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
base = "https://mainnet.base.org"
bnb = "https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3	"
bnb_testnet = "https://bsc-testnet.publicnode.com"
fraxtal = "https://rpc.frax.com"