[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3

evm_version = "shanghai"

ffi = true

remappings = [
"utils=lib/utils/",
"solady=lib/solady/src/",
"forge-std=lib/forge-std/src/",
"addressBook=lib/AddressBook/src/",
"address-book=lib/address-book/src/",
"@openzeppelin=lib/openzeppelin-contracts/",
"openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
"openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

optimizers_runs = 200

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"