[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 4

remappings = [
"utils=lib/utils/",
"solady=lib/solady/",
"forge-std=lib/forge-std/src/",
"@addressBook=lib/AddressBook/src/",
"@openzeppelin=lib/openzeppelin-contracts/",
"openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
"solidity-examples/=lib/solidity-examples/contracts/"
]

ffi = true
optimizers_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config


[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
base = "https://mainnet.base.org"
bnb = "https://bsc-mainnet.nodereal.io/v1/8ba50235e5794af7ba04e88181bb359f"
bnb_testnet = "https://bsc-testnet.publicnode.com"