
[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
allow_paths = ['../../node_modules']
fs_permissions = [{ access = "read-write", path = "./" }]
verbosity = 4
auto_detect_remappings = false

optimizers_runs = 200

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
base = "https://mainnet.base.org"
bnb = "https://bsc-mainnet.nodereal.io/v1/8ba50235e5794af7ba04e88181bb359f"
fraxtal = "https://rpc.frax.com"