[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.28"
evm_version = "cancun"

verbosity = 3
optimizer = true
optimizers_runs = 200

[etherscan]
bnb = { key = "${ETHERSCAN_KEY}", chain = 56 }
frax = { key = "${ETHERSCAN_KEY}", chain = 252 }
base = { key = "${ETHERSCAN_KEY}", chain = 8453 }
mainnet = { key = "${ETHERSCAN_KEY}", chain = 1 }
arbitrum = { key = "${ETHERSCAN_KEY}", chain = 42161 }
optimism = { key = "${ETHERSCAN_KEY}", chain = 10 }
zksync = { key = "${ETHERSCAN_KEY}", chain = 324 }
polygon = { key = "${ETHERSCAN_KEY}", chain = 137 }
polygonzkevm = { key = "${ETHERSCAN_KEY}", chain = 1101 }


[rpc_endpoints]
bnb = "https://bnb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
zksync = "https://zksync-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygonzkevm = "https://polygonzkevm-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
linea = "https://linea-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
