[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
solc = "0.8.28"

verbosity = 3
optimizer = true
optimizers_runs = 200

[fuzz]
runs = 50
max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail

[invariant]
runs = 500
depth = 10
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true


[etherscan]
bnb = { key = "${ETHERSCAN_KEY}", chain = 56 }
frax = { key = "${ETHERSCAN_KEY}", chain = 252 }
base = { key = "${ETHERSCAN_KEY}", chain = 8453 }
mainnet = { key = "${ETHERSCAN_KEY}", chain = 1 }
arbitrum = { key = "${ETHERSCAN_KEY}", chain = 42161 }
optimism = { key = "${ETHERSCAN_KEY}", chain = 10 }
zksync = { key = "${ETHERSCAN_KEY}", chain = 324 }
polygon = { key = "${ETHERSCAN_KEY}", chain = 137 }
polygonzkevm = { key = "${ETHERSCAN_KEY}", chain = 1101 }
sonic = { key = "${ETHERSCAN_KEY}", chain = 146 }

[rpc_endpoints]
sonic = "https://sonic.gateway.tenderly.co"
bnb = "https://bnb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
frax = "https://fraxtal.gateway.tenderly.co"
sepolia = "https://sepolia.gateway.tenderly.co"
base = "https://base.gateway.tenderly.co"
base-sepolia = "https://base-sepolia.gateway.tenderly.co"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
optimism = "https://optimism.gateway.tenderly.co"
zksync = "https://zksync-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygonzkevm = "https://polygonzkevm-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
