name: Lockers - Unit Tests

env:
  FOUNDRY_PROFILE: "ci"
  VYPER_VERSION: "0.3.10"
  ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

# This CI workflow is responsible of running the tests for the lockers package.
# It is triggered
# - only when the changes are made to the lockers package or the address-book package
# - when a PR is opened or when a push is made to the main branch
# - when a PR is opened or when a push is made to the feat/onlyboost-v2 branch
# - when the workflow is manually triggered
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/lockers/**"
      - ".github/workflows/lockers_unit-tests.yml" # this file
      - "packages/address-book/**" # dependency
      - "packages/interfaces/**" # dependency
    branches:
      - main
      - develop
  push:
    paths:
      - "packages/lockers/**"
      - ".github/workflows/lockers_unit-tests.yml" # this file
      - "packages/address-book/**" # dependency
      - "packages/interfaces/**" # dependency
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.4
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install vyper
        run: pipx install vyper==${{ env.VYPER_VERSION }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # the seed changes weekly to avoid burning through RPC allowance
      - name: Generate the weekly fuzz seed
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: Run tests
        working-directory: packages/lockers
        run: forge test -v
