name: Strategies - Unit Tests

env:
  FOUNDRY_PROFILE: "ci"

# This CI workflow is responsible of running the tests for the strategies package.
# It is triggered
# - only when the changes are made to the strategies package or the address-book package
# - when a PR is opened or when a push is made to the main branch
# - when a PR is opened or when a push is made to the feat/onlyboost-v2 branch
# - when the workflow is manually triggered
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/strategies/**"
      - "packages/address-book/**" # dependency
    branches:
      - main
      # temporary until the merge of onlyboost-v2
      - feat/onlyboost-v2
  push:
    paths:
      - "packages/strategies/**"
      - "packages/address-book/**" # dependency
    branches:
      - main
      # temporary until the merge of onlyboost-v2
      - feat/onlyboost-v2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show the Foundry config
        working-directory: packages/strategies
        run: forge config

      - name: Run tests
        working-directory: packages/strategies
        run: forge test
