name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  INFURA_KEY: ${{ secrets.INFURA_KEY }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'
      
      - name: Install Vyper@0.2.16
        run: pip install vyper==0.2.16

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
